version: "3"
services:
    web:
        container_name: flask_practice
        build: .
        command: python3 views.py
        working_dir: /app
        ports: 
            - 127.0.0.1:5020:5020
        volumes:
            - .:/app