version: "3"
services:
    web:
        container_name: flask_practice
        build: .
        command: >
            bash -c "
                pip install -r requirements.txt &&
                python3 config/settings.py &&
                python3 app/views.py
            "
        working_dir: /code
        ports: 
            - 127.0.0.1:5020:5020
        volumes:
            - .:/code
